# -*- coding: utf-8 -*-
"""progra_pi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhdPBEK-Ul1xK7Q6FDpL60RACh7Pl8x3
"""

import math

def calcular_distancia(coord1, coord2):
    # Fórmula para calcular la distancia entre dos puntos geográficos
    lat1, lon1 = coord1
    lat2, lon2 = coord2

    # Radio de la Tierra en kilómetros
    radio_tierra = 6371.0

    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)

    a = math.sin(dlat / 2)**2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    distancia = radio_tierra * c

    return distancia

def calcular_area(coords):

    # Fórmula del área de un polígono
    n = len(coords)
    area = 0.0

    for i in range(n - 1):
        area += (coords[i][0] * coords[i + 1][1]) - (coords[i + 1][0] * coords[i][1])

    area += (coords[n - 1][0] * coords[0][1]) - (coords[0][0] * coords[n - 1][1])

    area = abs(area) / 2.0

    return area

def main():
    print("¡Bienvenido al programa de cálculo de áreas y distancias!")

    while True:
        print("\n1. Calcular distancia entre dos puntos geográficos")
        print("2. Calcular área de un polígono")
        print("3. Salir")

        opcion = input("Seleccione una opción (1/2/3): ")

        if opcion == "1":
            # Entrada de coordenadas geográficas
            lat1 = float(input("Ingrese la latitud del primer punto: "))
            lon1 = float(input("Ingrese la longitud del primer punto: "))
            lat2 = float(input("Ingrese la latitud del segundo punto: "))
            lon2 = float(input("Ingrese la longitud del segundo punto: "))

            distancia = calcular_distancia((lat1, lon1), (lat2, lon2))
            print(f"La distancia entre los dos puntos es: {distancia:.2f} km")

        elif opcion == "2":
            # Entrada de coordenadas para el polígono
            n = int(input("Ingrese el número de vértices del polígono: "))
            coords = []

            for i in range(n):
                lat = float(input(f"Ingrese la latitud del vértice {i + 1}: "))
                lon = float(input(f"Ingrese la longitud del vértice {i + 1}: "))
                coords.append((lat, lon))

            area = calcular_area(coords)
            print(f"El área del polígono es: {area:.2f} unidades cuadradas")

        elif opcion == "3":
            print("¡Hasta luego! Gracias por usar el programa.")
            break

        else:
            print("Opción no válida. Por favor, seleccione 1, 2 o 3.")

if __name__ == "__main__":
    main()