# -*- coding: utf-8 -*-
"""programa_mejorado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JpU1q3u8nrCtfOvZV8Pm4uwsrjtujM1x
"""

import math

def calcular_distancia(coord1, coord2):
    """
    Calcula la distancia entre dos puntos geográficos utilizando la fórmula de Haversine.

    Args:
        coord1 (tuple): Coordenadas del primer punto (latitud, longitud).
        coord2 (tuple): Coordenadas del segundo punto (latitud, longitud).

    Returns:
        float: Distancia en kilómetros entre los dos puntos.
    """
    lat1, lon1 = coord1
    lat2, lon2 = coord2

    # Radio de la Tierra en kilómetros
    radio_tierra = 6371.0

    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)

    a = math.sin(dlat / 2)**2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    return radio_tierra * c

def calcular_area(coords):
    """
    Calcula el área de un polígono definido por sus vértices utilizando la fórmula del área del polígono.

    Args:
        coords (list of tuple): Lista de coordenadas (latitud, longitud) de los vértices del polígono.

    Returns:
        float: Área del polígono en unidades cuadradas.
    """
    n = len(coords)
    area = 0.0

    for i in range(n - 1):
        area += (coords[i][0] * coords[i + 1][1]) - (coords[i + 1][0] * coords[i][1])

    area += (coords[n - 1][0] * coords[0][1]) - (coords[0][0] * coords[n - 1][1])

    return abs(area) / 2.0

def mostrar_menu():
    """
    Muestra el menú principal del programa.
    """
    print("\n--- MENÚ PRINCIPAL ---")
    print("1. Calcular distancia entre dos puntos geográficos")
    print("2. Calcular área de un polígono")
    print("3. Salir")

def main():
    """
    Función principal del programa que interactúa con el usuario.
    """
    print("¡Bienvenido al programa de cálculo de áreas y distancias!")

    while True:
        mostrar_menu()
        opcion = input("Seleccione una opción (1/2/3): ").strip()

        if opcion == "1":
            try:
                # Entrada de coordenadas geográficas
                lat1 = float(input("Ingrese la latitud del primer punto: "))
                lon1 = float(input("Ingrese la longitud del primer punto: "))
                lat2 = float(input("Ingrese la latitud del segundo punto: "))
                lon2 = float(input("Ingrese la longitud del segundo punto: "))

                distancia = calcular_distancia((lat1, lon1), (lat2, lon2))
                print(f"La distancia entre los dos puntos es: {distancia:.2f} km")
            except ValueError:
                print("Error: Por favor, ingrese valores numéricos válidos.")

        elif opcion == "2":
            try:
                # Entrada de coordenadas para el polígono
                n = int(input("Ingrese el número de vértices del polígono: "))
                if n < 3:
                    print("Un polígono debe tener al menos 3 vértices.")
                    continue

                coords = []
                for i in range(n):
                    nombre = input(f"Ingrese el nombre del vértice {i + 1}: ").strip()
                    lat = float(input(f"Ingrese la latitud del vértice '{nombre}': "))
                    lon = float(input(f"Ingrese la longitud del vértice '{nombre}': "))
                    coords.append((lat, lon))

                area = calcular_area(coords)
                print(f"El área del polígono es: {area:.2f} unidades cuadradas")
            except ValueError:
                print("Error: Por favor, ingrese valores numéricos válidos.")

        elif opcion == "3":
            print("¡Hasta luego! Gracias por usar el programa.")
            break

        else:
            print("Opción no válida. Por favor, seleccione 1, 2 o 3.")

if __name__ == "__main__":
    main()